const RESPONSE_CODE = {
  // General
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  TECHNICAL_ERROR: 'TECHNICAL_ERROR',
  // For OTP
  OTP_BLOCKED: 'OTP_BLOCKED',
  OTP_GENERATION_BLOCKED: 'OTP_GENERATION_BLOCKED',
  OTP_VERIFICATION_FAILED: 'OTP_VERIFICATION_FAILED',
  OTP_VERIFICATION_LIMIT_EXCEEDED: 'OTP_VERIFICATION_LIMIT_EXCEEDED',
  // Deprecated TODO @ThienNguyen remove when auth done
  PARTY_NOT_ACTIVE: 'PARTY_NOT_ACTIVE',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  OTP_NOT_GENERATED: 'OTP_NOT_GENERATED',
  MOBILE_NUMBER_LOCKED: 'MOBILE_NUMBER_LOCKED',
  UNKNOWN_MOBILE_NUMBER: 'UNKNOWN_MOBILE_NUMBER',
  OTP_SEND_LIMIT_REACHED: 'OTP_SEND_LIMIT_REACHED',
  OTP_ENTRY_LIMIT_REACHED: 'OTP_ENTRY_LIMIT_REACHED',
  MOBILE_VERIFICATION_OTP_SENT: 'MOBILE_VERIFICATION_OTP_SENT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  ORIGINATION_EMPTY: 'ORIGINATION EMPTY',
  INVALID_SELFIE_IMAGE: 'INVALID_SELFIE_IMAGE',
  INVALID_CONSENT_ID: 'INVALID_CONSENT_ID',
};

const HTTP_CODE = {
  UNAUTHORIZED: 401,
  OK: 200,
};

const HTTP_MESSAGE = {
  UNAUTHORIZED: 'unauthorized',
};

export { RESPONSE_CODE, HTTP_CODE, HTTP_MESSAGE };
