export enum KEYCHAIN_RESULT_STATE {
  SUCCESS = 'SUCCESS',
  INVALID_DATA = 'INVALID_DATA',
  INVALID_KEYCHAIN = 'INVALID_KEYCHAIN',
  USER_CANCELED = 'USER_CANCELED',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
}

export const MEMORY_KEY = {
  CLIENT_AUTH: 'CLIENT_AUTH',
  USER_AUTH: 'USER_AUTH',
  SESSION_ID: 'SESSION_ID',
  HV_ACCESS_TOKEN: 'HV_ACCESS_TOKEN',
  ONBOARDING_TOKEN: 'ONBOARDING_TOKEN',
} as const;

export const STORAGE_KEY = {
  LANGUAGE: 'LANGUAGE',
  CUSTOMER_ID: 'CIF_ID',
  CUSTOMER_DETAIL: 'CIF_DETAIL',
  GUEST_INFORMATION: 'GUEST_INFORMATION',
  BIOMETRIC_SUPPORTED_TYPE: 'BIOMETRIC_SUPPORTED_TYPE',
  PIN_ENTRY_LIMIT: 'PIN_ENTRY_LIMIT',
  BIOMETRIC_ENTRY_LIMIT: 'BIOMETRIC_ENTRY_LIMIT',
  INTRO_VIRTUAL_CARD_DISABLE: 'INTRO_VIRTUAL_CARD_DISABLE',
  INIT_ROUTE: 'INIT_ROUTE',
  INIT_ROUTE_PROPS: 'INIT_ROUTE_PROPS',
  RESTART_REASON: 'RESTART_REASON',
  // For mock only
  MOCK_DEVICE_ID: 'MOCK_DEVICE_ID',
  CITY_LIST: 'CITY_LIST',
  DISTRICT_LIST: 'DISTRICT_LIST',
  WARD_LIST: 'WARD_LIST',

  HD_REQUEST_UID: 'HD_REQUEST_UID',
  //TODO Thuc phan remove
  HD_CITY_LIST: 'HD_CITY_LIST',
  HD_DISTRICT_LIST: 'HD_DISTRICT_LIST',
  HD_WARD_LIST: 'HD_WARD_LIST',
  APP_ROUTE_CONFIG: 'APP_ROUTE_CONFIG',

  INSTALL_ATTRIBUTION: 'INSTALL_ATTRIBUTION',
  LUCKY_SPIN_LAUNCHED_RULES: 'LUCKY_SPIN_LAUNCHED_RULES',
  FX_SALES: 'FX_SALES',
  VNEID_CONSENT_ID: 'VNEID_CONSENT_ID',

  //This address type specific for hd bank card los
  CARD_LOS_CITY_LIST: 'CARD_LOS_CITY_LIST',
  CARD_LOS_DISTRICT_LIST: 'CARD_LOS_DISTRICT_LIST',
  CARD_LOS_WARD_LIST: 'CARD_LOS_WARD_LIST',
  HOME_BG_REMOTE: 'HOME_BG_REMOTE',
  HOME_BG_TIMESTAMP: 'HOME_BG_TIMESTAMP',
} as const;

export const WHITE_LIST_STORAGE_KEY = [STORAGE_KEY.BIOMETRIC_SUPPORTED_TYPE];
